<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>291b3013-8370-48c8-8bcf-96dce500dda7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strata.Application\Strata.Application.csproj" />
    <ProjectReference Include="..\Strata.Infrastructure\Strata.Infrastructure.csproj" />
  </ItemGroup>

</Project>
